# baseurl: https://lagosrusers.netlify.app/
baseurl: https://lagosrusers.com/
title: LagosRusersGroup
theme: hugo-universal-theme
languageCode: en-us
defaultContentLanguage: en
disqusShortname: LagosRUsersGroup
googleAnalytics: ''
summaryLength: 70
paginate: 10
pluralizelisttitles: no
menu:
  main:
    - identifier: menu.home
      name: Home
      url: /
      weight: 1
    - identifier: menu.blog
      name: Blog
      url: /blog/
      weight: 2
    - identifier: menu.meetup
      name: Meetup
      url: /meetup/
      weight: 3
    - identifier: menu.datathon
      name: Datathon
      url: /datathon/
      weight: 4
    - identifier: menu.about
      name: About
      url: /contact/
      weight: 5
    - name: Contact
      parent: menu.about
      url: /contact/
      weight: 1
    - identifier: menu.video
      name: Video
      url: 'https://youtube.com/channel/UCTyVNJF2D0BegashtEk3aPg'
      weight: 6      
  topbar:
    - name: Email
      pre: <i class='fas fa-2x fa-envelope'></i>
      url: mailto:lagos.r.users.group@gmail.com
      weight: 1
    - name: GitHub
      pre: <i class='fab fa-2x fa-github'></i>
      url: https://github.com/LagosRUsersGroup
      weight: 2
    - name: GitHub
      pre: <i class='fab fa-2x fa-youtube'></i>
      url: https://youtube.com/channel/UCTyVNJF2D0BegashtEk3aPg
      weight: 2    
    - name: Facebook
      pre: <i class='fab fa-2x fa-facebook'></i>
      url: http://facebook.com
      weight: 3
    - name: Twitter
      pre: <i class='fab fa-2x fa-twitter'></i>
      url: http://twitter.com/lagosrusers
      weight: 4
    - name: WhatsApp
      pre: <i class='fab fa-2x fa-whatsapp'></i>
      url: https://chat.whatsapp.com/HVMlwFWUWgu3kIk61snHAt
      weight: 5
    - name: Telegram
      pre: <i class='fab fa-2x fa-telegram'></i>
      url: https://t.me/+HoAEqTJ3JYsyZWE0
      weight: 6      

params:
  about_us: <p>Lagos R User Group is a community of R Programming Language users in Lagos.</p>
  address: ""
  author: LagosRUsersGroup
  carouselHomepage:
    auto_play: yes
    enable: yes
    pagination_speed: 1000
    slide_speed: 2000
  carouselCustomers:
    auto_play: no
    items: 6
    pagination_speed: 1000
    slide_speed: 2000
  carouselTestimonials:
    auto_play: no
    items: 4
    pagination_speed: 1000
    slide_speed: 2000
  clients:
    enable: yes
    subtitle: ''
    title: Our Sponsors
  contact_form_ajax: no
  contact_url: /contact
  copyright: Copyright (c) 2022, LagosRUsersGroup; all rights reserved.
  date_format: January 2, 2006
  default_sharing_image: img/sharing-default.png
  defaultDescription: ""
  defaultKeywords:
    - LagosRUsersGroup
    - meetup
    - R
  disabled_logo: no
  dropdown_mouse_over: no
  enableGoogleMaps: no
  enableRecaptchaInContactForm: no
  facebook_site: ''
  features:
    cols: 3
    enable: yes
  footer:
    recent_posts:
      enable: yes
  formspree_action: https://formspree.io/sample/of/endpoint
  googleMapsApiKey: AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY
  googleRecaptchaKey: site_key_for_google_recaptcha
  latitude: '-12.043333'
  logo: img/logo.png
  logo_small: img/logo-small.png
  logo_text: LagosRUsersGroup
  longitude: '-77.028333'
  mainSections: blog
  recent_posts:
    enable: yes
    hide_summary: no
    subtitle: Checkout our latest blog posts.
    title: From our Blog
  see_more:
    enable: yes
    icon: far fa-file-alt
    link_text: 'Meetup'
    link_url: 'https://www.meetup.com/LagosRUsers/join'
    title: Join the Community
    subtitle: ''
    
  style: blue
  testimonials:
    enable: no
    subtitle: What the community member are saying.
    title: Testimonials
  topbar:
    enable: yes
    text: "
      \     <p class=\"hidden-md hidden-lg\"><a href=\"tel:+234 \" data-animate-hover=\"pulse\"><i
      class=\"fas fa-phone\"></i></a>\r\n      <a href=\"mailto:lagos.r.users.group@gmail.com\"
      data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\r\n      </p>\r\n
      \     "
  twitter_site: LagosRUsersGroup
  viewMorePostLink: /blog/
  widgets:
    categories: yes
    search: yes
    tags: yes
permalinks:
  blog: /blog/:year/:month/:day/:filename/
taxonomies:
  author: authors
  category: categories
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
